
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ChiTietDonDatHang
{

    public int PRODUCT_ID { get; set; }

    public int DONDATHANG_ID { get; set; }

    public string TENSP { get; set; }

    public Nullable<int> SOLUONG { get; set; }

    public Nullable<double> GIA { get; set; }

    public Nullable<double> THANHTIEN { get; set; }



    public virtual DonDatHang DonDatHang { get; set; }

    public virtual Product Product { get; set; }

}

}
