//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int CONTACT_ID { get; set; }
        public string HOTENNV { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string NOIDUNG { get; set; }
        public string HINHANH { get; set; }
    }
}
