
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DonDatHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DonDatHang()
    {

        this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();

    }


    public int DONDATHANG_ID { get; set; }

    public Nullable<int> KHACHHANG_ID { get; set; }

    public Nullable<bool> DATHANHTOAN { get; set; }

    public bool DAHUY { get; set; }

    public bool DAXOA { get; set; }

    public Nullable<System.DateTime> NGAYLAPDON { get; set; }

    public Nullable<System.DateTime> NGAYGIAOHANG { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }

    public virtual KhachHang KhachHang { get; set; }

}

}
