//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int CART_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int RESTOCKS_ID { get; set; }
        public Nullable<int> SLSP { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Restock Restock { get; set; }
    }
}
