
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class KhachHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KhachHang()
    {

        this.DonDatHangs = new HashSet<DonDatHang>();

    }


    public int KHACHHANG_ID { get; set; }

    public string TENKH { get; set; }

    public Nullable<int> SDT { get; set; }

    public string EMAIL { get; set; }

    public string USERNAME { get; set; }

    public string UPASSWORD { get; set; }

    public string DIACHI { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DonDatHang> DonDatHangs { get; set; }

}

}
