//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NEWS_ID { get; set; }
        public string TIEUDE { get; set; }
        public string HINHANH { get; set; }
        public string CHITIET { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
    }
}
